apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-medusa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-medusa
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-medusa
    spec:
      containers:
      - name: medusa
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-medusa
spec:
  ports:
  - port: 80
  selector:
    app: {{ .Release.Name }}-medusa
