apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-orchestrator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-orchestrator-role
rules:
- apiGroups: ["", "apps", "networking.k8s.io", "batch"]
  resources: ["namespaces", "deployments", "services", "ingresses", "secrets", "configmaps", "persistentvolumeclaims", "jobs", "pods", "pods/log"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-orchestrator-binding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-orchestrator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-orchestrator-role
  apiGroup: rbac.authorization.k8s.io
